#!/usr/bin/python3
import re
import os
import subprocess

# HOTSOS GLOBALS
VERBOSITY_LEVEL = os.environ.get('VERBOSITY_LEVEL', '/')
DATA_ROOT = os.environ.get('DATA_ROOT', '/')

SERVICES = ["etcdctl",
            "calicoctl",
            "kubectl2",
            "kubelet",
            "containerd-shim",
            "containerd",
            "dockerd"]

print("kubernetes:")


def get_ps():
    if DATA_ROOT == '/':
        ps = subprocess.check_output(['ps'])
        return ps.decode('UTF-8').splitlines()
    else:
        path = os.path.join(DATA_ROOT,
                            "ps")
        if os.path.exists(path):
            return open(path, 'r').readlines()


service_info = {}
for svc in SERVICES:
    for line in get_ps():
        ret = re.compile(r".+({})\s+.+".format(svc)).match(line)
        if ret:
            if svc in service_info:
                service_info[svc] += 1
            else:
                service_info[svc] = 1

print("  services:")
for svc in service_info:
    print("    - {} ({})".format(svc, service_info[svc]))


print("  pods:")
for pod in os.listdir(os.path.join(DATA_ROOT, "var/log/pods")):
    print("    - {}".format(pod))

print("  containers:")
for container in os.listdir(os.path.join(DATA_ROOT, "var/log/containers")):
    print("    - {}".format(container))
